//
//  ServiceNames.m
//  Bonjour Browser
//
//  Created by PHPdev32 on 1/29/14.
//  Licensed under GPLv3, full text at http://www.gnu.org/licenses/gpl-3.0.txt
//

#import "ServiceNames.h"
#import <arpa/inet.h>
#import <net/if_dl.h>
#import <sys/socket.h>

static NSDictionary *services;
static NSCharacterSet *separator;

NSArray* SocksToStrings(NSArray *addresses){
    NSMutableArray *temp = [NSMutableArray array];
    for(NSData *addr in addresses) {
        NSString *str = [NSString string];
        switch (((struct sockaddr *)[addr bytes])->sa_family) {
            case AF_INET:{
                struct sockaddr_in *sock = (struct sockaddr_in *)[addr bytes];
                char ad[INET_ADDRSTRLEN];
                inet_ntop(AF_INET, &sock->sin_addr, ad, INET_ADDRSTRLEN);
                str = [NSString stringWithFormat:@"%s:%u",ad,ntohs(sock->sin_port)];
                break;
            }
            case AF_INET6:{
                struct sockaddr_in6 *sock = (struct sockaddr_in6 *)[addr bytes];
                char ad[INET6_ADDRSTRLEN];
                inet_ntop(AF_INET6, &sock->sin6_addr, ad, INET6_ADDRSTRLEN);
                str = [NSString stringWithFormat:@"%s@%u",ad,ntohs(sock->sin6_port)];
                break;
            }
            case AF_LINK:{
                struct sockaddr_dl *sock = (struct sockaddr_dl *)[addr bytes];
                char *name = NULL;
                char *ll = NULL;
                strlcpy(name, sock->sdl_data, sock->sdl_nlen);
                strlcpy(ll, sock->sdl_data+sock->sdl_nlen, sock->sdl_alen);
                str = [NSString stringWithFormat:@"%s %s",name,ll];
                break;
            }
        }
        [temp addObject:str];
    }
    return [temp copy];
}

@implementation ServiceNames
+(NSString *)parse:(NSString *)descriptor{
    return [[descriptor componentsSeparatedByCharactersInSet:separator] objectAtIndex:1];
}
+(NSString *)resolve:(NSString *)service{
    NSString *resolved = [services objectForKey:service];
    return (resolved==nil)?service:resolved;
}
+(void) initialize {
    separator = [NSCharacterSet characterSetWithCharactersInString:@"_."];
    /* curl -s http://www.dns-sd.org/ServiceTypes.html | grep '^<b>'  | sed -e 's/ protocol$//' -e 's/ Protocol$//' -e 's:":\\":g' -e 's;^<b>\(.*\)</b> *\(.*\)$;@"\1":@"\2",;w dnssd.txt' */
    services = @{
                 @"1password":@"1Password Password Manager data sharing and synchronization",
                 @"a-d-sync":@"Altos Design Synchronization",
                 @"abi-instrument":@"Applied Biosystems Universal Instrument Framework",
                 @"accessdata-f2d":@"FTK2 Database Discovery Service",
                 @"accessdata-f2w":@"FTK2 Backend Processing Agent Service",
                 @"accessone":@"Strix Systems 5S/AccessOne",
                 @"accountedge":@"MYOB AccountEdge",
                 @"acp-sync":@"Access Control Policy Synchronization",
                 @"acrobatsrv":@"Adobe Acrobat",
                 @"acs-ctl-ds":@"Access Control Device",
                 @"acs-ctl-gw":@"Access Control Gateway",
                 @"actionitems":@"ActionItems",
                 @"activeraid":@"Active Storage Proprietary Device Management",
                 @"activeraid-ssl":@"Encrypted transport of Active Storage Proprietary Device Management",
                 @"addressbook":@"Address-O-Matic",
                 @"addressbooksrv":@"Address Book Server used for contacts and calendar synchronisation",
                 @"adnodes":@"difusi Cloud based plug & play network synchronization",
                 @"adobe-shadow":@"Adobe Shadow Server",
                 @"adobe-vc":@"Adobe Version Cue",
                 @"adisk":@"Automatic Disk Discovery",
                 @"adpro-setup":@"ADPRO Security Device Setup",
                 @"aecoretech":@"Apple Application Engineering Services",
                 @"aeroflex":@"Aeroflex instrumentation and software",
                 @"aerohive-proxy":@"Aerohive Proxy Configuration Service",
                 @"afpovertcp":@"Apple File Sharing",
                 @"airdrop":@"Airdrop",
                 @"airplay":@"Protocol for streaming of audio/video content",
                 @"airport":@"AirPort Base Station",
                 @"airpreview":@"Coda AirPreview",
                 @"airprojector":@"AirProjector",
                 @"airsharing":@"Air Sharing",
                 @"airsharingpro":@"Air Sharing Pro",
                 @"aloe-gwp":@"Aloe Gateway",
                 @"aloe-pp":@"Aloe Pairing",
                 @"amba-cam":@"Ambarella Cameras",
                 @"amiphd-p2p":@"P2PTapWar Sample Application from \"iPhone SDK Development\" Book",
                 @"ams-htm":@"Proprietary protocol for Accu-Med HTM",
                 @"animolmd":@"Animo License Manager",
                 @"animobserver":@"Animo Batch Server",
                 @"anquetsync":@"Anquet map synchronization between desktop and handheld devices",
                 @"antrmai":@"ANT Galio web services",
                 @"appelezvous":@"Appelezvous",
                 @"apple-ausend":@"Apple Audio Units",
                 @"apple-mobdev":@"Apple Mobile Device",
                 @"apple-midi":@"Apple MIDI",
                 @"apple-sasl":@"Apple Password Server",
                 @"applerdbg":@"Apple Remote Debug Services (OpenGL Profiler)",
                 @"appletv":@"Apple TV",
                 @"appletv-itunes":@"Apple TV discovery of iTunes",
                 @"appletv-pair":@"Apple TV Pairing",
                 @"aquamon":@"AquaMon",
                 @"asr":@"Apple Software Restore",
                 @"arcnet":@"Arcturus Networks Inc. Hardware Services",
                 @"aroundsound":@"AroundSound's information sharing",
                 @"astnotify":@"Asterisk Caller-ID Notification Service",
                 @"astralite":@"Astralite",
                 @"async":@"address-o-sync",
                 @"atlassianapp":@"Atlassian Application (JIRA, Confluence, Fisheye, Crucible, Crowd, Bamboo) discovery service",
                 @"av":@"Allen Vanguard Hardware Service",
                 @"avatars":@"Libravatar federated avatar hosting service.",
                 @"avatars-sec":@"Libravatar federated avatar hosting service.",
                 @"axis-video":@"Axis Video Cameras",
                 @"auth":@"Authentication Service",
                 @"b3d-convince":@"3M Unitek Digital Orthodontic System",
                 @"babyphone":@"BabyPhone",
                 @"bdsk":@"BibDesk Sharing",
                 @"beacon":@"Beacon Remote Service",
                 @"beamer":@"Beamer Data Sharing",
                 @"beatpack":@"BeatPack Synchronization Server for BeatMaker",
                 @"beatsdirect":@"Beats Direct allows for the discovery and control of devices",
                 @"beep":@"Xgrid Technology Preview",
                 @"bfagent":@"BuildForge Agent",
                 @"bigbangchess":@"Big Bang Chess",
                 @"bigbangmancala":@"Big Bang Mancala",
                 @"bitflit":@"Data transfer service",
                 @"bittorrent":@"BitTorrent Zeroconf Peer Discovery",
                 @"blackbook":@"Little Black Book Information Exchange",
                 @"bluevertise":@"BlueVertise Network Protocol (BNP)",
                 @"boardplus":@"board plus application transfer",
                 @"booked-sync":@"Booked communication",
                 @"bookworm":@"Bookworm Client Discovery",
                 @"bootps":@"Bootstrap Protocol Server",
                 @"boundaryscan":@"Proprietary",
                 @"bousg":@"Bag Of Unusual Strategy Games",
                 @"boxraysrvr":@"Boxray Devices Host Server",
                 @"bri":@"RFID Reader Basic Reader Interface",
                 @"bridgeprotocol":@"JSON RPC Bridge",
                 @"bsqdea":@"Backup Simplicity",
                 @"buddycloud-api":@"buddycloud API",
                 @"busycal":@"BusySync Calendar Synchronization",
                 @"caldav":@"Calendaring Extensions to WebDAV (CalDAV) - non-TLS",
                 @"caldavs":@"Calendaring Extensions to WebDAV (CalDAV) - over TLS",
                 @"caltalk":@"CalTalk",
                 @"carddav":@"vCard Extensions to WebDAV (CardDAV) - non-TLS",
                 @"carddavs":@"vCard Extensions to WebDAV (CardDAV) - over TLS",
                 @"cardsend":@"Card Send",
                 @"carousel":@"Carousel Player",
                 @"cctv":@"IP and Closed-Circuit Television for Securitiy applications",
                 @"cheat":@"The Cheat",
                 @"chess":@"Project Gridlock",
                 @"chfts":@"Fluid Theme Server",
                 @"chili":@"The CHILI Radiology System",
                 @"ciao":@"Ciao Arduino",
                 @"cip4discovery":@"Discovery of JDF (CIP4 Job Definition Format) enabled devices",
                 @"clipboard":@"Clipboard Sharing",
                 @"clique":@"Clique Link-Local Multicast Chat Room",
                 @"clscts":@"Oracle CLS Cluster Topology Service",
                 @"collection":@"Published Collection Object",
                 @"com-ocs-es-mcc":@"ElectraStar media centre control",
                 @"contactserver":@"Now Contact",
                 @"corroboree":@"Corroboree Server",
                 @"cpnotebook2":@"NoteBook 2",
                 @"csi-mmws":@"Canfield Scientific Inc - Mirror Mobile Web Services",
                 @"cvspserver":@"CVS PServer",
                 @"cw-codetap":@"CodeWarrior HTI Xscale PowerTAP",
                 @"cw-dpitap":@"CodeWarrior HTI DPI PowerTAP",
                 @"cw-oncetap":@"CodeWarrior HTI OnCE PowerTAP",
                 @"cw-powertap":@"CodeWarrior HTI COP PowerTAP",
                 @"cytv":@"CyTV",
                 @"daap":@"Digital Audio Access Protocol (iTunes)",
                 @"dacp":@"Digital Audio Control Protocol (iTunes)",
                 @"dancepartner":@"Dance partner application for iPhone",
                 @"dataturbine":@"Open Source DataTurbine Streaming Data Middleware",
                 @"dbaudio":@"d&b audiotechnik remote network",
                 @"dccp-ping":@"ping/traceroute using DCCP",
                 @"device-info":@"Device Info",
                 @"devonsync":@"DEVONthink synchronization",
                 @"dictation":@"Use of a dictation service by a hand-held device",
                 @"difi":@"EyeHome",
                 @"disconnect":@"DisConnect Peer to Peer Game",
                 @"dist-opencl":@"Distributed OpenCL discovery",
                 @"distcc":@"Distributed Compiler",
                 @"ditrios":@"Ditrios SOA Framework",
                 @"divelogsync":@"Dive Log Data Sharing and Synchronization",
                 @"dlpx-sp":@"Delphix Session",
                 @"dltimesync":@"Local Area Dynamic Time Synchronisation",
                 @"dns-llq":@"DNS Long-Lived Queries",
                 @"dns-sd":@"DNS Service Discovery",
                 @"dns-update":@"DNS Dynamic Update Service",
                 @"domain":@"Domain Name Server",
                 @"dop":@"Roar (Death of Productivity)",
                 @"dossier":@"Vortimac Dossier",
                 @"dpap":@"Digital Photo Access Protocol (iPhoto)",
                 @"dropcopy":@"DropCopy",
                 @"dsgsync":@"Datacolor SpyderGallery Desktop Sync",
                 @"dsl-sync":@"Data Synchronization Protocol for Discovery Software products",
                 @"dtrmtdesktop":@"Desktop Transporter Remote Desktop",
                 @"dvbservdsc":@"DVB Service Discovery",
                 @"dxtgsync":@"Documents To Go Desktop Sync",
                 @"ea-dttx-poker":@"Protocol for EA Downtown Texas Hold 'em",
                 @"earphoria":@"Earphoria",
                 @"easyspndlg-sync":@"Sync service for the Easy Spend Log app",
                 @"eb-amuzi":@"Amuzi peer-to-peer session synchronization",
                 @"ebms":@"ebXML Messaging",
                 @"ecms":@"Northrup Grumman/Mission Systems/ESL Data Flow",
                 @"ebreg":@"ebXML Registry",
                 @"ecbyesfsgksc":@"Net Monitor Anti-Piracy Service",
                 @"edcp":@"LaCie Ethernet Disk Configuration",
                 @"eeg":@"EEG System Discovery across local and wide area networks",
                 @"efkon-elite":@"EFKON Lightweight Interface to Traffic Events",
                 @"egistix":@"Egistix Auto-Discovery",
                 @"eheap":@"Interactive Room Software Infrastructure (Event Sharing)",
                 @"embrace":@"DataEnvoy",
                 @"enphase-envoy":@"Enphase Energy Envoy",
                 @"ep":@"Endpoint Protocol (EP) for use in Home Automation systems",
                 @"eppc":@"Remote AppleEvents",
                 @"erp-scale":@"Pocket Programs ERP-Scale Server Discovery",
                 @"esp":@"Extensis Server",
                 @"eucalyptus":@"Eucalyptus Discovery",
                 @"eventserver":@"Now Up-to-Date",
                 @"evp":@"EvP - Generic EVENT",
                 @"evs-notif":@"EVS Notification Center",
                 @"ewalletsync":@"Synchronization Protocol for Ilium Software's eWallet",
                 @"example":@"Example Service Type",
                 @"exb":@"Exbiblio Cascading Service",
                 @"exec":@"Remote Process Execution",
                 @"extensissn":@"Extensis Serial Number",
                 @"eyetvsn":@"EyeTV Sharing",
                 @"facespan":@"FaceSpan",
                 @"fairview":@"Fairview Device Identification",
                 @"faxstfx":@"FAXstf",
                 @"feed-sharing":@"NetNewsWire 2.0",
                 @"firetask":@"Firetask task sharing and synchronization",
                 @"fish":@"Fish",
                 @"fix":@"Financial Information Exchange (FIX)",
                 @"fjork":@"Fjork",
                 @"fl-purr":@"FilmLight Cluster Power Control Service",
                 @"flightdmp":@"Flight Data Monitoring",
                 @"flir-ircam":@"FLIR Infrared Camera",
                 @"fmpro-internal":@"FileMaker Pro",
                 @"fmserver-admin":@"FileMaker Server Administration Communication Service",
                 @"fontagentnode":@"FontAgent Pro",
                 @"foxtrot-serv":@"FoxTrot Search Server Discovery Service",
                 @"foxtrot-start":@"FoxTrot Professional Search Discovery Service",
                 @"frameforge-lic":@"FrameForge License",
                 @"freehand":@"FreeHand MusicPad Pro Interface",
                 @"frog":@"Frog Navigation Systems",
                 @"ftp":@"File Transfer",
                 @"ftpcroco":@"Crocodile FTP Server",
                 @"fv-cert":@"Fairview Certificate",
                 @"fv-key":@"Fairview Key",
                 @"fv-time":@"Fairview Time/Date",
                 @"garagepad":@"Entrackment Client Service",
                 @"gbs-smp":@"SnapMail",
                 @"gbs-stp":@"SnapTalk",
                 @"gforce-ssmp":@"G-Force Control via SoundSpectrum's SSMP TCP",
                 @"glasspad":@"GlassPad Data Exchange",
                 @"glasspadserver":@"GlassPadServer Data Exchange",
                 @"glrdrvmon":@"OpenGL Driver Monitor",
                 @"googlecast":@"Google Chromecast",
                 @"goorstop":@"For iOS Application named GoOrStop",
                 @"gpnp":@"Grid Plug and Play",
                 @"grillezvous":@"Roxio ToastAnywhere(tm) Recorder Sharing",
                 @"groovesquid":@"Groovesquid Democratic Music Control",
                 @"growl":@"Growl",
                 @"gucam-http":@"Image Data Transfer API for Wi-Fi Camera Devices over HTTP",
                 @"guid":@"Special service type for resolving by GUID (Globally Unique Identifier)",
                 @"h323":@"H.323 Real-time audio, video and data communication call setup",
                 @"helix":@"MultiUser Helix Server",
                 @"help":@"HELP command",
                 @"hg":@"Mercurial web-based repository access",
                 @"hinz":@"HINZMobil Synchronization",
                 @"hmcp":@"Home Media Control",
                 @"home-sharing":@"iTunes Home Sharing",
                 @"homeauto":@"iDo Technology Home Automation",
                 @"homeconnect":@"Home Connect",
                 @"honeywell-vid":@"Honeywell Video Systems",
                 @"hotwayd":@"Hotwayd",
                 @"howdy":@"Howdy messaging and notification",
                 @"hpr-bldlnx":@"HP Remote Build System for Linux-based Systems",
                 @"hpr-bldwin":@"HP Remote Build System for Microsoft Windows Systems",
                 @"hpr-db":@"Identifies systems that house databases for the Remote Build System and Remote Test System",
                 @"hpr-rep":@"HP Remote Repository for Build and Test Results",
                 @"hpr-toollnx":@"HP Remote System that houses compilers and tools for Linux-based Systems",
                 @"hpr-toolwin":@"HP Remote System that houses compilers and tools for Microsoft Windows Systems",
                 @"hpr-tstlnx":@"HP Remote Test System for Linux-based Systems",
                 @"hpr-tstwin":@"HP Remote Test System for Microsoft Windows Systems",
                 @"hs-off":@"Hobbyist Software Off Discovery",
                 @"htsp":@"Home Tv Streaming",
                 @"http":@"World Wide Web HTML-over-HTTP",
                 @"https":@"HTTP over SSL/TLS",
                 @"htvncconf":@"HomeTouch Vnc Configuration",
                 @"hydra":@"SubEthaEdit",
                 @"hyperstream":@"Atempo HyperStream deduplication server",
                 @"iad1":@"BBN IAD",
                 @"iad2":@"BBN IAD",
                 @"iad3":@"BBN IAD",
                 @"iax":@"Inter Asterisk eXchange, ease-of-use NAT friendly open VoIP",
                 @"ibiz":@"iBiz Server",
                 @"ica-networking":@"Image Capture Networking",
                 @"ican":@"Northrup Grumman/TASC/ICAN",
                 @"ichalkboard":@"iChalk",
                 @"ichat":@"iChat 1.0",
                 @"icloud-ds":@"iCloud Unknown",
                 @"iconquer":@"iConquer",
                 @"icontrolbox":@"A Remote Control Application service used to control Computers on a Local Area Network",
                 @"idata":@"Generic Data Acquisition and Control",
                 @"idsync":@"SplashID Synchronization Service",
                 @"ifolder":@"Published iFolder",
                 @"ihouse":@"Idle Hands iHouse",
                 @"ii-drills":@"Instant Interactive Drills",
                 @"ii-konane":@"Instant Interactive Konane",
                 @"ilynx":@"iLynX",
                 @"imap":@"Internet Message Access",
                 @"imidi":@"iMidi",
                 @"imgsync":@"Protocol synchronizing Image data",
                 @"ims-ni":@"Noise Inspector",
                 @"indigo-dvr":@"Indigo Security Digital Video Recorders",
                 @"infboard":@"InfBoard interactive whiteboard",
                 @"inova-ontrack":@"Inova Solutions OnTrack Display",
                 @"idcws":@"Intermec Device Configuration Web Services",
                 @"iota":@"iotaMed medical records server",
                 @"ipbroadcaster":@"IP Broadcaster",
                 @"ipp":@"IPP (Internet Printing Protocol)",
                 @"ipspeaker":@"IP Speaker Control",
                 @"ir-hvac-000":@"HVAC SMIL Server",
                 @"irelay":@"iRelay application discovery service",
                 @"irmc":@"Intego Remote Management Console",
                 @"irradiatd-iclip":@"iClip clipboard transfer",
                 @"iscsi":@"Internet Small Computer Systems Interface (iSCSI)",
                 @"isparx":@"iSparx",
                 @"ispq-vc":@"iSpQ VideoChat",
                 @"ishare":@"iShare",
                 @"isticky":@"iSticky",
                 @"istorm":@"iStorm",
                 @"isynchronize":@"iSynchronize data synchronization",
                 @"itap-publish":@"iTap Publishing Service",
                 @"itis-device":@"IT-IS International Ltd. Device",
                 @"itsrc":@"iTunes Socket Remote Control",
                 @"ivef":@"Inter VTS Exchange Format",
                 @"iwork":@"iWork Server",
                 @"jcan":@"Northrup Grumman/TASC/JCAN",
                 @"jeditx":@"Jedit X",
                 @"jini":@"Jini Service Discovery",
                 @"jnx-kcsync":@"jollys keychain cloud sync",
                 @"jtag":@"Proprietary",
                 @"jukebox":@"Jukebox Request Service",
                 @"kerberos":@"Kerberos",
                 @"kerberos-adm":@"Kerberos Administration",
                 @"keynoteaccess":@"KeynoteAccess is used for sending remote requests/responses when controlling a slideshow with Keynote Remote",
                 @"keynotepairing":@"KeynotePairing is used to pair Keynote Remote with Keynote",
                 @"ktp":@"Kabira Transaction Platform",
                 @"la-maint":@"IMP Logical Address Maintenance",
                 @"labyrinth":@"Labyrinth local multiplayer",
                 @"lan2p":@"Lan2P Peer-to-Peer Network",
                 @"lapse":@"Gawker",
                 @"lanrevagent":@"LANrev Agent",
                 @"lanrevserver":@"LANrev Server",
                 @"ldap":@"Lightweight Directory Access",
                 @"leaf":@"Lua Embedded Application Framework",
                 @"lexicon":@"Lexicon Vocabulary Sharing",
                 @"liaison":@"Liaison",
                 @"library":@"Delicious Library 2 Collection Data Sharing",
                 @"libratone":@"Protocol for setup and control of Libratone products",
                 @"licor":@"LI-COR Biosciences instrument discovery",
                 @"llrp":@"RFID reader Low Level Reader",
                 @"llrp-secure":@"RFID reader Low Level Reader Protocol over SSL/TLS",
                 @"lobby":@"Gobby",
                 @"logicnode":@"Logic Pro Distributed Audio",
                 @"login":@"Remote Login a la Telnet",
                 @"lonbridge":@"Echelon LonBridge Server",
                 @"lontalk":@"LonTalk over IP (ANSI 852)",
                 @"lonworks":@"Echelon LNS Remote Client",
                 @"lsys-appserver":@"Linksys One Application Server API",
                 @"lsys-camera":@"Linksys One Camera API",
                 @"lsys-ezcfg":@"LinkSys EZ Configuration",
                 @"lsys-oamp":@"LinkSys Operations, Administration, Management, and Provisioning",
                 @"lumiere":@"A protocol to remotely control DMX512 devices over the network",
                 @"lumis-lca":@"Lumis Cache Appliance",
                 @"lux-dtp":@"Lux Solis Data Transport",
                 @"lxi":@"LXI",
                 @"lyrics":@"iPod Lyrics Service",
                 @"macfoh":@"MacFOH",
                 @"macfoh-admin":@"MacFOH admin services",
                 @"macfoh-audio":@"MacFOH audio stream",
                 @"macfoh-events":@"MacFOH show control events",
                 @"macfoh-data":@"MacFOH realtime data",
                 @"macfoh-db":@"MacFOH database",
                 @"macfoh-remote":@"MacFOH Remote",
                 @"macminder":@"Mac Minder",
                 @"maestro":@"Maestro Music Sharing Service",
                 @"magicdice":@"Magic Dice Game",
                 @"mandos":@"Mandos Password Server",
                 @"matrix":@"MATRIX Remote AV Switching",
                 @"mavlink":@"MAVLink Micro Air Vehicle Communication",
                 @"mbconsumer":@"MediaBroker++ Consumer",
                 @"mbproducer":@"MediaBroker++ Producer",
                 @"mbserver":@"MediaBroker++ Server",
                 @"mconnect":@"ClairMail Connect",
                 @"mcrcp":@"MediaCentral",
                 @"mediaboard1":@"MediaBoardONE Asset and Information Manager data sharing and synchronization",
                 @"mediatap":@"Mediatap streaming",
                 @"mesamis":@"Mes Amis",
                 @"mimer":@"Mimer SQL Engine",
                 @"mi-raysat":@"Mental Ray for Maya",
                 @"mn-passage":@"A Remote Control Application service used to control Computers on a Local Area Network",
                 @"modolansrv":@"modo LAN Services",
                 @"mogeneti-auth":@"Authentication service for Mogeneti Software Applications",
                 @"moneysync":@"SplashMoney Synchronization Service",
                 @"moneyworks":@"MoneyWorks Gold and MoneyWorks Datacentre network service",
                 @"moodring":@"Bonjour Mood Ring tutorial program",
                 @"mother":@"Mother script server",
                 @"movieslate":@"MovieSlate digital clapperboard",
                 @"mp3sushi":@"MP3 Sushi",
                 @"mqtt":@"IBM MQ Telemetry Transport Broker",
                 @"mslingshot":@"Martian SlingShot",
                 @"mumble":@"Mumble VoIP communication",
                 @"musicmachine":@"Protocol for a distributed music playing service",
                 @"mysync":@"MySync",
                 @"mttp":@"MenuTunes Sharing",
                 @"mxim-art2":@"Maxim Integrated Products Automated Roadtest Mk II",
                 @"mxim-ice":@"Maxim Integrated Products In-circuit Emulator",
                 @"mxs":@"MatrixStore",
                 @"nasmon":@"Proprietary communication protocol for NAS Monitor",
                 @"ncbroadcast":@"Network Clipboard Broadcasts",
                 @"ncdirect":@"Network Clipboard Direct Transfers",
                 @"ncount-issuer":@"The issuer service in the n-Count electronic value transfer system",
                 @"ncsyncserver":@"Network Clipboard Sync Server",
                 @"nodel":@"Lightweight event based control protocol utilising JavaScript Object Notation",
                 @"neoriders":@"NeoRiders Client Discovery",
                 @"net-assistant":@"Apple Remote Desktop",
                 @"net2display":@"Vesa Net2Display",
                 @"netrestore":@"NetRestore",
                 @"netvu-video":@"AD Group NetVu Connected Video",
                 @"newton-dock":@"Escale",
                 @"nextcap":@"Proprietary communication protocol for NextCap capture solution",
                 @"nfs":@"Network File System - Sun Microsystems",
                 @"ni":@"National Instruments Network Device",
                 @"ni-rt":@"National Instruments Real-Time Target",
                 @"ni-sysapi":@"National Instruments System API Service",
                 @"nssocketport":@"DO over NSSocketPort",
                 @"ntlx-arch":@"American Dynamics Intellex Archive Management Service",
                 @"ntlx-ent":@"American Dynamics Intellex Enterprise Management Service",
                 @"ntlx-video":@"American Dynamics Intellex Video Service",
                 @"ntp":@"Network Time",
                 @"ntx":@"Tenasys",
                 @"obf":@"Observations Framework",
                 @"objective":@"Means for clients to locate servers in an Objective (http://www.objective.com) instance.",
                 @"oca":@"Insecure OCP.1, TCP/IP implementation of the Object Control Architecture",
                 @"ocasec":@"Secure OCP.1, TCP/IP implementation of the Object Control Architecture",
                 @"oce":@"Oce Common Exchange",
                 @"od-master":@"OpenDirectory Master",
                 @"odproxy":@"OpenDirectory Proxy",
                 @"odabsharing":@"OD4Contact",
                 @"odisk":@"Optical Disk Sharing",
                 @"officetime-sync":@"OfficeTime Synchronization",
                 @"ofocus-conf":@"OmniFocus setting configuration",
                 @"ofocus-sync":@"OmniFocus document synchronization",
                 @"olpc-activity1":@"One Laptop per Child activity",
                 @"oma-bcast-sg":@"OMA BCAST Service Guide Discovery Service",
                 @"omadm-bootstrap":@"Open Mobile Alliance (OMA) Device Management (DM) Bootstrap Server Discovery Service",
                 @"omni-bookmark":@"OmniWeb",
                 @"omni-live":@"Service for remote control of Omnisphere virtual instrument",
                 @"openbase":@"OpenBase SQL",
                 @"opencu":@"Conferencing",
                 @"oprofile":@"oprofile server",
                 @"oscit":@"Open Sound Control Interface Transfer",
                 @"osxsvr":@"AppleShare IP WebAdmin",
                 @"ovready":@"ObjectVideo OV Ready",
                 @"owhttpd":@"OWFS (1-wire file system) web server",
                 @"owserver":@"OWFS (1-wire file system) server",
                 @"parentcontrol":@"Remote Parental Controls",
                 @"passwordwallet":@"PasswordWallet Data Synchronization",
                 @"pcast":@"Mac OS X Podcast Producer Server",
                 @"p2pchat":@"Peer-to-Peer Chat (Sample Java Bonjour application)",
                 @"p2pstorage-sec":@"DataBOND p2p storage",
                 @"pairandshare":@"Pair & Share data",
                 @"panoply":@"Panoply multimedia composite transfer",
                 @"parabay-p2p":@"Parabay P2P",
                 @"parity":@"PA-R-I-Ty (Public Address - Radio - Intercom - Telefony)",
                 @"parliant":@"PhoneValet Anywhere",
                 @"pdl-datastream":@"Printer Page Description Language Data Stream (vendor-specific)",
                 @"pgpkey-hkp":@"Horowitz Key Protocol (HKP)",
                 @"pgpkey-http":@"PGP Keyserver using HTTP/1.1",
                 @"pgpkey-https":@"PGP Keyserver using HTTPS",
                 @"pgpkey-ldap":@"PGP Keyserver using LDAP",
                 @"pgpkey-mailto":@"PGP Key submission using SMTP",
                 @"photoparata":@"Photo Parata Event Photography Software",
                 @"photosmithsync":@"Photosmith's iPad to Lightroom sync",
                 @"pictua":@"Pictua Intercommunication",
                 @"piesync":@"pieSync Computer to Computer Synchronization",
                 @"piu":@"Pedestal Interface Unit by RPM-PSI",
                 @"poch":@"Parallel OperatiOn and Control Heuristic (Pooch)",
                 @"podcastproxy":@"Protocol for communication between Podcast",
                 @"pokeeye":@"Communication channel for \"Poke Eye\" Elgato EyeTV remote controller",
                 @"pop3":@"Post Office Protocol - Version 3",
                 @"postgresql":@"PostgreSQL Server",
                 @"powereasy-erp":@"PowerEasy ERP",
                 @"powereasy-pos":@"PowerEasy Point of Sale",
                 @"pplayer-ctrl":@"Piano Player Remote Control",
                 @"presence":@"Peer-to-peer messaging / Link-Local Messaging",
                 @"print-caps":@"Retrieve a description of a device's print capabilities",
                 @"printer":@"Spooler (more commonly known as \"LPR printing\" or \"LPD printing\")",
                 @"printopia":@"Port to allow for administration and control of \"\"Printopia\"\" application software, which provides printing services to mobile users",
                 @"profilemac":@"Profile for Mac medical practice management software",
                 @"prolog":@"Prolog",
                 @"protonet":@"Protonet node and service discovery",
                 @"psap":@"Progal Service Advertising",
                 @"psia":@"Physical Security Interoperability Alliance",
                 @"pstmailsync":@"File synchronization protocol for Pst Mail Sync",
                 @"pstmailsync-ssl":@"Secured file synchronization protocol for Pst Mail Sync",
                 @"ptnetprosrv2":@"PTNetPro Service",
                 @"ptp":@"Picture Transfer",
                 @"ptp-init":@"Picture Transfer Protocol(PTP) Initiator",
                 @"ptp-req":@"PTP Initiation Request",
                 @"puzzle":@"Protocol used for puzzle games",
                 @"pvaccess":@"Experimental Physics and Industrial Control System",
                 @"qbox":@"QBox Appliance Locator",
                 @"qttp":@"QuickTime Transfer",
                 @"quad":@"Distributed Game Data",
                 @"quinn":@"Quinn Game Server",
                 @"rakket":@"Rakket Client",
                 @"radiotag":@"RadioTAG: Event tagging for radio services",
                 @"radiovis":@"RadioVIS: Visualisation for radio services",
                 @"radioepg":@"RadioEPG: Electronic Programme Guide for radio services",
                 @"radioport":@"RadioPort Message Service",
                 @"raop":@"Remote Audio Output Protocol (AirTunes)",
                 @"rbr":@"RBR Instrument Communication",
                 @"rce":@"PowerCard",
                 @"rdp":@"Windows Remote Desktop",
                 @"realplayfavs":@"RealPlayer Shared Favorites",
                 @"recipe":@"Recipe Sharing",
                 @"recipe-box":@"The Recipe Box Exchange",
                 @"recipe-sharing":@"Recipe Sharing",
                 @"recolive-cc":@"Remote Camera Control",
                 @"remote":@"Remote Device Control",
                 @"remoteburn":@"LaCie Remote Burn",
                 @"renderpipe":@"ARTvps RenderDrive/PURE Renderer",
                 @"rendezvouspong":@"RendezvousPong",
                 @"renkara-sync":@"Renkara synchronization",
                 @"resacommunity":@"Community Service",
                 @"resol-vbus":@"RESOL VBus",
                 @"retrospect":@"Retrospect backup and restore service",
                 @"rfb":@"Remote Frame Buffer (used by VNC)",
                 @"rfbc":@"Remote Frame Buffer Client (Used by VNC viewers in listen-mode)",
                 @"rfid":@"RFID Reader Mach1(tm)",
                 @"rgb":@"RGB Spectrum Device Discovery",
                 @"riousbprint":@"Remote I/O USB Printer",
                 @"roku-rcp":@"Roku Control",
                 @"rowmote":@"Rowmote Control",
                 @"rql":@"RemoteQuickLaunch",
                 @"rsmp-server":@"Remote System Management Protocol (Server Instance)",
                 @"rsync":@"Rsync",
                 @"rtsp":@"Real Time Streaming",
                 @"rubygems":@"RubyGems GemServer",
                 @"rym-rrc":@"Raymarine remote control",
                 @"safarimenu":@"Safari Menu",
                 @"sallingbridge":@"Salling Clicker Sharing",
                 @"sallingclicker":@"Salling Clicker Service",
                 @"salutafugijms":@"Salutafugi Peer-To-Peer Java Message Service Implementation",
                 @"sandvox":@"Sandvox",
                 @"savagesoft":@"Proprietary Client Server",
                 @"sc-golf":@"StrawberryCat Golf",
                 @"scanner":@"Bonjour Scanning",
                 @"schick":@"Schick",
                 @"scone":@"Scone",
                 @"scpi-raw":@"IEEE 488.2 (SCPI) Socket",
                 @"scpi-telnet":@"IEEE 488.2 (SCPI) Telnet",
                 @"sdsharing":@"Speed Download",
                 @"see":@"SubEthaEdit 2",
                 @"seeCard":@"seeCard",
                 @"senteo-http":@"Senteo Assessment Software",
                 @"sentillion-vlc":@"Sentillion Vault System",
                 @"sentillion-vlt":@"Sentillion Vault Systems Cluster",
                 @"sepvsync":@"SEPV Application Data Synchronization",
                 @"serendipd":@"serendiPd Shared Patches for Pure Data",
                 @"servereye":@"ServerEye AgentContainer Communication",
                 @"servermgr":@"Mac OS X Server Admin",
                 @"services":@"DNS Service Discovery",
                 @"sessionfs":@"Session File Sharing",
                 @"sflow":@"sFlow traffic monitoring",
                 @"sftp-ssh":@"Secure File Transfer Protocol over SSH",
                 @"shell":@"like exec, but automatic authentication is performed as for login server.",
                 @"shifter":@"Window Shifter server",
                 @"shipsgm":@"Swift Office Ships",
                 @"shipsinvit":@"Swift Office Ships",
                 @"shoppersync":@"SplashShopper Synchronization Service",
                 @"shoutcast":@"Nicecast",
                 @"simmon":@"Medical simulation patient monitor syncronisation",
                 @"simusoftpong":@"simusoftpong iPhone game",
                 @"sip":@"Session Initiation Protocol, signalling protocol for VoIP",
                 @"sipuri":@"Session Initiation Protocol Uniform Resource Identifier",
                 @"sironaxray":@"Sirona Xray",
                 @"skillscapture":@"The protocol is used to transfer database records between an iOS device to a Mac OS X computer",
                 @"skype":@"Skype",
                 @"sleep-proxy":@"Sleep Proxy Server",
                 @"slimcli":@"SliMP3 Server Command-Line Interface",
                 @"slimhttp":@"SliMP3 Server Web Interface",
                 @"smartenergy":@"Smart Energy Profile",
                 @"smartsocket":@"home control",
                 @"smb":@"Server Message Block over TCP/IP",
                 @"sms":@"Short Text Message Sending and Delivery Status Service",
                 @"smsync":@"Syncellence file synchronization",
                 @"soap":@"Simple Object Access",
                 @"socketcloud":@"Socketcloud distributed application framework",
                 @"sox":@"Simple Object eXchange",
                 @"sparechange":@"SpareChange data sharing",
                 @"spearcat":@"sPearCat Host Discovery",
                 @"spidap":@"Sierra Photonics Inc. data",
                 @"spike":@"Shared Clipboard",
                 @"spincrisis":@"Spin Crisis",
                 @"spl-itunes":@"launchTunes",
                 @"spr-itunes":@"netTunes",
                 @"splashsync":@"SplashData Synchronization Service",
                 @"spres":@"SongPresenter",
                 @"ss-sign":@"Samsung Smart Interaction for Group Network",
                 @"ss-sign-disc":@"Samsung Smart Interaction for Group Network Discovery",
                 @"spx-hmp":@"SpinetiX HMP",
                 @"ssh":@"SSH Remote Login",
                 @"ssscreenshare":@"Screen Sharing",
                 @"strateges":@"Strateges",
                 @"sge-exec":@"Sun Grid Engine (Execution Host)",
                 @"sge-qmaster":@"Sun Grid Engine (Master)",
                 @"soda":@"Secure On Device API",
                 @"souschef":@"SousChef Recipe Sharing",
                 @"sparql":@"SPARQL Protocol and RDF Query Language",
                 @"sqp":@"Square Connect Control",
                 @"stanza":@"Lexcycle Stanza service for discovering shared books",
                 @"stickynotes":@"Sticky Notes",
                 @"stotp":@"One Time Pad Synchronisation",
                 @"submission":@"Message Submission",
                 @"supple":@"Supple Service",
                 @"surveillus":@"Surveillus Networks Discovery",
                 @"svn":@"Subversion",
                 @"swcards":@"Signwave Card Sharing",
                 @"switcher":@"Wireless home control remote control",
                 @"swordfish":@"Swordfish Protocol for Input/Output",
                 @"swyp":@"Framework for transferring any file from any app, to any app on any device: simply with a swÿp",
                 @"sxqdea":@"Synchronize! Pro X",
                 @"sybase-tds":@"Sybase Server",
                 @"syncopation":@"Syncopation Synchronization Protocol by Sonzea",
                 @"syncqdea":@"Synchronize! X Plus 2.0",
                 @"synergy":@"Synergy Peer Discovery",
                 @"synksharing":@"SynkSharing synchronization",
                 @"taccounting":@"Data Transmission and Synchronization",
                 @"tango":@"Tango Remote Control",
                 @"tapinoma-ecs":@"Tapinoma Easycontact receiver",
                 @"taskcoachsync":@"Task Coach Two-way Synchronization Protocol for iPhone",
                 @"tbricks":@"tbricks internal",
                 @"tcode":@"Time Code",
                 @"tcu":@"Tracking Control Unit by RPM-PSI",
                 @"te-faxserver":@"TE-SYSTEMS GmbH Fax Server Daemon",
                 @"teamlist":@"ARTIS Team Task",
                 @"teleport":@"teleport",
                 @"telnet":@"Telnet",
                 @"tenir-rc":@"Proprietary",
                 @"tera-fsmgr":@"Terascala Filesystem Manager",
                 @"tera-mp":@"Terascala Maintenance",
                 @"test-ok":@"Test Controller Card",
                 @"tf-redeye":@"ThinkFlood RedEye IR bridge",
                 @"tftp":@"Trivial File Transfer",
                 @"thumbwrestling":@"tinkerbuilt Thumb Wrestling game",
                 @"ticonnectmgr":@"TI Connect Manager Discovery Service",
                 @"timbuktu":@"Timbuktu",
                 @"tinavigator":@"TI Navigator Hub 1.0 Discovery Service",
                 @"tivo-device":@"TiVo Device",
                 @"tivo-hme":@"TiVo Home Media Engine",
                 @"tivo-mindrpc":@"TiVo RPC",
                 @"tivo-music":@"TiVo Music",
                 @"tivo-photos":@"TiVo Photos",
                 @"tivo-remote":@"TiVo Remote",
                 @"tivo-videos":@"TiVo Videos",
                 @"todogwa":@"2Do Sync Helper Tool for Mac OS X and PCs",
                 @"tomboy":@"Tomboy",
                 @"toothpicserver":@"ToothPics Dental Office Support Server",
                 @"touch-able":@"iPhone and iPod touch Remote Controllable",
                 @"touch-remote":@"iPhone and iPod touch Remote Pairing",
                 @"tri-vis-client":@"triCerat Simplify Visibility Client",
                 @"tri-vis-server":@"triCerat Simplify Visibility Server",
                 @"tryst":@"Tryst",
                 @"tsbiis":@"The Social Broadband Interference Information Sharing",
                 @"tt4inarow":@"Trivial Technology's 4 in a Row",
                 @"ttcheckers":@"Trivial Technology's Checkers",
                 @"ttp4daemon":@"TechTool Pro 4 Anti-Piracy Service",
                 @"tunage":@"Tunage Media Control Service",
                 @"tuneranger":@"TuneRanger",
                 @"twinlevel":@"detect sanitary product",
                 @"tzrpc":@"TZ-Software remote procedure call based synchronization",
                 @"ubertragen":@"Ubertragen",
                 @"uddi":@"Universal Description, Discovery and Integration",
                 @"uddi-inq":@"Universal Description, Discovery and Integration Inquiry",
                 @"uddi-pub":@"Universal Description, Discovery and Integration Publishing",
                 @"uddi-sub":@"Universal Description, Discovery and Integration Subscription",
                 @"uddi-sec":@"Universal Description, Discovery and Integration Security",
                 @"upnp":@"Universal Plug and Play",
                 @"urlbookmark":@"URL Advertising",
                 @"uswi":@"Universal Switching Corporation products",
                 @"utest":@"uTest",
                 @"uwsgi":@"Unbit Web Server Gateway Interface",
                 @"ve-decoder":@"American Dynamics VideoEdge Decoder Control Service",
                 @"ve-encoder":@"American Dynamics VideoEdge Encoder Control Service",
                 @"ve-recorder":@"American Dynamics VideoEdge Recorder Control Service",
                 @"virtualdj":@"VirtualDJ Remote Control",
                 @"visel":@"visel Q-System services",
                 @"volley":@"Volley",
                 @"vos":@"Virtual Object System (using VOP/TCP)",
                 @"vue4rendercow":@"VueProRenderCow",
                 @"vxi-11":@"VXI-11 TCP/IP Instrument",
                 @"wakeywakey":@"Proprietary",
                 @"walkietalkie":@"Walkie Talkie",
                 @"wd-2go":@"NAS Service",
                 @"we-jell":@"Proprietary collaborative messaging",
                 @"webdav":@"World Wide Web Distributed Authoring and Versioning (WebDAV)",
                 @"webdavs":@"WebDAV over SSL/TLS",
                 @"webissync":@"WebIS Sync",
                 @"wedraw":@"weDraw document sharing",
                 @"whamb":@"Whamb",
                 @"whistler":@"Honeywell Video Systems",
                 @"wicop":@"WiFi Control Platform",
                 @"wired":@"Wired Server",
                 @"witap":@"WiTap Sample Game",
                 @"witapvoice":@"witapvoice",
                 @"wkgrpsvr":@"Workgroup Server Discovery",
                 @"workstation":@"Workgroup Manager",
                 @"wormhole":@"Roku Cascade Wormhole",
                 @"workgroup":@"Novell collaboration workgroup",
                 @"writietalkie":@"Writie Talkie Data Sharing",
                 @"ws":@"Web Services",
                 @"wtc-heleos":@"Wyatt Technology Corporation HELEOS",
                 @"wtc-qels":@"Wyatt Technology Corporation QELS",
                 @"wtc-rex":@"Wyatt Technology Corporation Optilab rEX",
                 @"wtc-viscostar":@"Wyatt Technology Corporation ViscoStar",
                 @"wtc-wpr":@"Wyatt Technology Corporation DynaPro Plate Reader",
                 @"wwdcpic":@"PictureSharing sample code",
                 @"x-on":@"x-on services synchronisation",
                 @"x-plane9":@"x-plane9",
                 @"xcodedistcc":@"Xcode Distributed Compiler",
                 @"xcsp":@"Xcode Service",
                 @"xgate-rmi":@"xGate Remote Management Interface",
                 @"xgrid":@"Xgrid",
                 @"xmiserver":@"XMI Systems home terminal local connection",
                 @"xmms2":@"XMMS2 IPC",
                 @"xmp":@"Xperientia Mobile",
                 @"xmpp-client":@"XMPP Client Connection",
                 @"xmpp-server":@"XMPP Server Connection",
                 @"xsanclient":@"Xsan Client",
                 @"xsanserver":@"Xsan Server",
                 @"xsansystem":@"Xsan System",
                 @"xserveraid":@"XServe Raid",
                 @"xsync":@"Xserve RAID Synchronization",
                 @"xtimelicence":@"xTime License",
                 @"xtshapro":@"xTime Project",
                 @"xul-http":@"XUL (XML User Interface Language) transported over HTTP",
                 @"yakumo":@"Yakumo iPhone OS Device Control",
                 @"z-wave":@"Z-Wave Service Discovery",
                 @"zeromq":@"High performance brokerless messaging",
                 @"zigbee-bridge":@"ZigBee Bridge device",
                 @"zigbee-gateway":@"ZigBee IP Gateway"};
}

@end
